export const dummyProfileData = {
  crewID: 45892,
  name: "Arjun Mehta",
  email: "arjun.mehta@skywings.com",

  // Addresses
  addresses1: "221B Aviation Residency",
  addresses2: "Indira Nagar",
  addresses3: "Tower 14",
  city: "Bengaluru",
  state: "Karnataka",
  zip: "560038",

  // Phone Numbers
  phone1Number: "+919812345601",
  phone2Number: "+919812345602",
  phone3Number: "+919812345603",
  phone4Number: "+919812345604",
  phone5Number: "+919812345605",
  phone6Number: "+919812345606",

  // Next of Kin
  kinName: "Priya Mehta",
  kinRltn: "Wife",
  kinCont: "+919812345699",

  // Marital + Family
  marStatus: 1,
  fullName: "Arjun Ramesh Mehta",
  marriageDate: "2014-11-12",
  residenceCtr: "India",
  socialSecrty: "INPNS8934M",

  // Mailing Address
  mailAddresses1: "Sky Heights Apartment",
  mailAddresses2: "HSR Layout",
  mailAddresses3: "Block C",
  mailCity: "Bengaluru",
  mailState: "Karnataka",
  mailZip: "560102",

  // Passport 1
  passport: "Z4583921",
  passpDate: "2019-02-15",
  passPlace: "Bengaluru",
  passCntr: "IND",
  natlity: "Indian",
  natCod: "IN",

  // Passport 2
  passport2: "Z9821345",
  passpDate2: "2021-06-30",
  passPlace2: "Mumbai",
  pass2Cntr: "IND",
  natlity2: "Indian",
  natCod2: "IN",

  // License 1
  lcneNum: "CPL-IND-457839",
  lcneDate: "2015-07-20",
  lcnePlace: "Delhi",
  lcneType: "Commercial",
  licCtrCode: "IND",

  // License 2
  lcneNum2: "PPL-IND-982134",
  lcneDate2: "2020-01-15",
  lcnePlace2: "Mumbai",
  lcneType2: "Private",
  licCtrCode2: "IND",

  // Misc IDs
  permit: "PERM-458921",
  contract: "CNTR-839210",
  certifNum: "CERT-998231",

  // Birth Details
  birthPlace: "Ahmedabad",
  birthState: "Gujarat",
  birthCntr: "IND",
  dob: "1986-04-25",
  gender: "Male",

  // Passport Names
  passpnNames1: "Arjun",
  passpnNames2: "Ramesh",
  passpnNames3: "Mehta",

  // Secondary Email
  email2: "arjun.m.alt@skywings.com",

  // Job Info
  base: "Delhi",
  designation: "Captain",
  senior: "Yes",
  doj: "2009-08-01",

  // Physical Info
  physicalInfoHeight: "178 cm",
  physicalInfoHairClr: "Black",
  physicalInfoEyeClr: "Brown",
  physicalInfoWeight: "72 kg",

  // Family
  spousId: "SP-4589",
};

export const myDummyProfile = {
  success: true,
  message: "Data retrieved successfully.",
  data: [
    {
      crewID: 104,
      name: "PAUL, MUNISH KUMAR",
      email: "MUNISH.PAUL@GOINDIGO.IN",
      addresses1: "FLAT NO - 1104,  ANTIRIKSH GREENS,",
      addresses2: "DOORDARSHAN WELFARE SOCIETY",
      addresses3: "PLOT 8, SECTOR 45",
      phone1Number: "9958112006",
      phone2Number: "1234567890",
      phone3Number: "",
      phone4Number: "",
      phone5Number: "",
      phone6Number: "",
      city: "GURGAON",
      state: "",
      zip: "122003",
      kinName: "Sandhya Paul",
      kinRltn: "wife",
      kinCont: "9958012006",
      marStatus: 1,
      fullName: "IPLTM20200063642",
      marriageDate: "",
      residenceCtr: "IND",
      socialSecrty: "",
      mailCity: "NEW DELHII",
      mailState: "",
      mailZip: "110017",
      passport: "Z8223809",
      passpDate: "20250224",
      passPlace: "DELHI",
      passport2: "",
      passpDate2: "",
      passPlace2: "",
      lcneNum: "ATPL 2984",
      lcneDate: "",
      lcnePlace: "DAW DEL",
      lcneType: "9380",
      permit: "",
      contract: "TEST",
      lcneNum2: "(A)10155",
      lcneDate2: "",
      lcnePlace2: "DOT DEL",
      lcneType2: "",
      birthPlace: "NANGAL PUNJAB",
      natlity: "IN",
      natlity2: "",
      passCntr: "IND",
      pass2Cntr: "",
      birthCntr: "IND",
      natCod: "IND",
      natCod2: "",
      licCtrCode: "IND",
      licCtrCode2: "",
      certifNum: "1-1471/2005L2",
      birthState: "PB",
      passpnNames1: "PAUL",
      passpnNames2: "MUNISH",
      passpnNames3: "KUMAR",
      email2: "MUNISHPAUL@GMAIL.COM",
      mailAddresses1: "D32, GROUND FLOOR, MARG 12 SAKETT",
      mailAddresses2: "",
      mailAddresses3: "IPLTM20200063641",
      base: "DEL",
      designation: "CP",
      physicalInfoHeight: "0",
      physicalInfoHairClr: "",
      physicalInfoEyeClr: "123456789abc",
      physicalInfoWeight: "0",
      spousId: "0",
      senior: "3",
      doj: "",
      dob: "1961-10-06",
      gender: "M",
      qualification: null,
      passportVaild: null,
    },
  ],
  error: [],
};
export const promoBannerDummyData = {
  success: true,
  message: "",
  data: [
    {
      Id: "60c72b2f9b1e8b3f4c8e4d1a",
      BannerHeading: "Big Discounts!",
      BannerContent: "Enjoy up to 50% off on all items.",
      IsUploadedFile: true,
      UploadedFilePath:
        "https://media.istockphoto.com/id/814423752/photo/eye-of-model-with-colorful-art-make-up-close-up.jpg?s=612x612&w=0&k=20&c=l15OdMWjgCKycMMShP8UK94ELVlEGvt7GmB_esHWPYE=",
      IsColorBanner: false,
      ColorBanner: "#808080",
      IsCTA: true,
      CTANAME: "Shop Now",
      CTAURL: "https://example.com/sale", // 1. cta website/app url 2. pdf url
      IsCTAPDF: false,
    },
    {
      Id: "60c72b2f9b1e8b3f4c8e4d1a",
      BannerHeading: "Big Discounts!",
      BannerContent: "Enjoy up to 50% off on all items.",
      IsUploadedFile: false,
      UploadedFilePath: "",
      IsColorBanner: true,
      ColorBanner: "#FF0000",
      IsCTA: true,
      CTANAME: "Shop Now",
      CTAURL: "https://example.com/sale.pdf",
      IsCTAPDF: true,
    },
  ],
  error: [],
};

export const favouritesDummyData = {
  success: true,
  message: "",
  data: [
    {
      AppName: "ACM",
      IsFavorite: false,
      AppIcon: "",
      CreatedBy: "",
      CreatedOn: "2025-07-11T10:06:27.512+00:00",
      UpdatedBy: "",
      UpdatedOn: "",
      IsActive: true,
      IsDeleted: false,
      Link: "",
      IsAPP: true,
    },
    {
      AppName: "Logistics",
      IsFavorite: false,
      AppIcon: "",
      CreatedBy: "",
      CreatedOn: "2025-07-11T10:06:27.512+00:00",
      UpdatedBy: "",
      UpdatedOn: "",
      IsActive: true,
      IsDeleted: false,
      Link: "",
      IsAPP: false,
    },
    {
      AppName: "Documents",
      IsFavorite: false,
      AppIcon: "",
      CreatedBy: "",
      CreatedOn: "2025-07-11T10:06:27.512+00:00",
      UpdatedBy: "",
      UpdatedOn: "",
      IsActive: true,
      IsDeleted: false,
      Link: "",
      IsAPP: false,
    },
    {
      AppName: "Links Library",
      IsFavorite: false,
      AppIcon: "",
      CreatedBy: "",
      CreatedOn: "2025-07-11T10:06:27.512+00:00",
      UpdatedBy: "",
      UpdatedOn: "",
      IsActive: true,
      IsDeleted: false,
      Link: "",
      IsAPP: false,
    },
    {
      AppName: "Sector Pay",
      IsFavorite: false,
      AppIcon: "",
      CreatedBy: "",
      CreatedOn: "2025-07-11T10:06:27.512+00:00",
      UpdatedBy: "",
      UpdatedOn: "",
      IsActive: true,
      IsDeleted: false,
      Link: "",
      IsAPP: false,
    },
    {
      AppName: "Allowance",
      IsFavorite: false,
      AppIcon: "",
      CreatedBy: "",
      CreatedOn: "2025-07-11T10:06:27.512+00:00",
      UpdatedBy: "",
      UpdatedOn: "",
      IsActive: true,
      IsDeleted: false,
      Link: "",
      IsAPP: false,
    },
    {
      AppName: "CPFO",
      IsFavorite: false,
      AppIcon: "",
      CreatedBy: "",
      CreatedOn: "2025-07-11T10:06:27.512+00:00",
      UpdatedBy: "",
      UpdatedOn: "",
      IsActive: true,
      IsDeleted: false,
      Link: "",
      IsAPP: false,
    },
    {
      AppName: "Videos",
      IsFavorite: false,
      AppIcon: "",
      CreatedBy: "",
      CreatedOn: "2025-07-11T10:06:27.512+00:00",
      UpdatedBy: "",
      UpdatedOn: "",
      IsActive: true,
      IsDeleted: false,
      Link: "",
      IsAPP: false,
    },
  ],
  error: [],
};
export const dummyData = {
  loginUser: {
    name: "Jack",
  },
};

export const flightData = [
  {
    id: "1",
    flightNumber: "62E 3034",
    departure: "DEL",
    departureTerminal: "2",
    arrival: "BKK",
    arrivalTerminal: "1",
    duration: "4h 55m",
    departureTime: "Jan 17, 23:00",
    arrivalTime: "Jan 18, 03:00",
    reportingTime: "Jan 17, 22:00",
    bayNumber: "23",
    regNumber: "VT-IXJ",
    temperature: "25ºC",
    weatherCondition: "Clear Skies",
    status: "BA Pending",
    nextTripCountdown: "02:33:40",
    duty: "FLT",
  },

  { id: "3", duty: "VAC" },
  { id: "2", duty: "SMT" },
  { id: "4", duty: "SCK" },
  { id: "5", duty: "OFG" },
  { id: "6", duty: "SBY" },
  { id: "7", duty: "MTL" },
];

export const flightDataInside = [
  {
    id: "1",
    flightNumber: "62E 3034",
    departure: "DEL",
    departureTerminal: "2",
    arrival: "BKK",
    arrivalTerminal: "1",
    duration: "4h 55m",
    departureTime: "Jan 17, 23:00",
    arrivalTime: "Jan 18, 03:00",
    reportingTime: "Jan 17, 22:00",
    bayNumber: "23",
    regNumber: "VT-IXJ",
    temperature: "25ºC",
    weatherCondition: "Clear Skies",
    status: "BA Pending",
    nextTripCountdown: "02:33:40",
    duty: "FLT",
  },

  { id: "2", duty: "SMT" },
];

export const flightSummaryData = [
  { title: "Block Hours", value: "71:00", icon: "clock" },
  { title: "Duty Hours", value: "110:00", icon: "briefcase" },
  { title: "Total Flights", value: "32", icon: "clock" },
  { title: "Total Operating", value: "26", icon: "briefcase" },
  { title: "Total DHT/DHF", value: "6", icon: "clock" },
  { title: "Total Layovers", value: "2", icon: "briefcase" },
];
export const tabs = ["Flight", "Crew", "Weather", "Training"];

export const cockpitCrew = [
  {
    id: 1,
    name: "Smriti",
    role: "Captain",
    iga: "83274",
    baStatus: "Completed",
    image:
      "https://media.istockphoto.com/id/628330740/photo/portrait-of-a-beautifull-smiling-man.jpg?s=612x612&w=0&k=20&c=t10Nhvv-kzaSEdYpL0-dUvN5_Z9YV58vvDGmwcjZrIk=",
    isVerify: true,
  },
  {
    id: 2,
    name: "Arjun",
    role: "First Officer",
    iga: "73211",
    baStatus: "Incomplete",
    image:
      "https://media.istockphoto.com/id/1289220545/photo/beautiful-woman-smiling-with-crossed-arms.jpg?s=612x612&w=0&k=20&c=qmOTkGstKj1qN0zPVWj-n28oRA6_BHQN8uVLIXg0TF8=",
  },
];

export const cabinCrew = [
  {
    id: 3,
    name: "Neeraj Goel",
    role: "Captain",
    iga: "65211",
    baStatus: "Incomplete",
    image:
      "https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg",
  },
];

export const flightDetailsRow = [
  { id: 1, title: "Model", value: "Captain" },
  { id: 2, title: "Tail No.", value: "Unknow" },
  { id: 3, title: "Status", value: "Pending" },
];

export const flightRevisions = [
  {
    id: "1",
    oldFlight: "BKK to DXB",
    newFlight: "BKK to HAN",
    oldFlightTime: "Jan 17, 03:45 to Jan 18, 05:35",
    newFlightTime: "Jan 18, 01:30 to Jan 19, 05:30",
    oldFlightNumber: "6E 3034",
    newFlightNumber: "6E 2024",
    changedDate: "Jan 11, 04:00",
    acknowledgedDate: "Jan 12, 08:00",
  },
  {
    id: "2",
    oldFlight: "BKK to DXB",
    newFlight: "BKK to HAN",
    oldFlightTime: "Jan 17, 03:45 to Jan 18, 05:35",
    newFlightTime: "Jan 18, 01:30 to Jan 19, 05:30",
    oldFlightNumber: "6E 3034",
    newFlightNumber: "6E 2024",
    changedDate: "Jan 11, 04:00",
    acknowledgedDate: "Jan 15, 08:00",
  },
];

export const monthlyRoaster = [
  {
    date: "01-04-2025",
    reportingTime: "01-01-2025, 04:30",
    data: [
      {
        from: "DEL",
        fromTerminal: 3,
        to: "DXB",
        toTerminal: 1,
        departure: "01-01-2025, 06:00",
        arrival: "01-01-2025, 08:30",
        flightNumber: "6E 112",
        aircraft: "A320",
        transit: "45m",
        status: "Revision",
        date: "01-01-2025",
      },
      {
        from: "DXB",
        fromTerminal: 1,
        to: "JFK",
        toTerminal: 2,
        departure: "01-01-2025, 14:00",
        arrival: "02-01-2025, 05:00",
        flightNumber: "EK 201",
        aircraft: "A380",
        status: "Acknowledged",
        date: "01-01-2025",
      },
    ],
  },
];

// data/favouritesData.ts
export const favouritesData = [
  { id: "1", label: "ACM", icon: "users" },
  { id: "2", label: "Logistics", icon: "users" },
  { id: "3", label: "Documents", icon: "users" },
  { id: "4", label: "Links", icon: "users" },
  { id: "5", label: "ACM", icon: "users" },
  { id: "6", label: "Logistics", icon: "users" },
  { id: "7", label: "Documents", icon: "users" },
  { id: "8", label: "Links", icon: "users" },
];

export const dummyDataForAnnouncement = [
  {
    id: 1,
    data: {
      title: "Paper is Passe",
      description: "Redefining the Way We Communicate.",
    },
  },
  {
    id: 2,
    data: {
      title: "A New Era",
      description: "Digital transformation at its finest.",
    },
  },
];

// Dummy data
export const hotelData = {
  name: "Lemon Tree Bangalore",
  address1: "Lemon Tree Premier, Bangalore",
  address2: "Lemon Tree Premier, Ulsoor Lake, Bengaluru",
  phone: "+91-9898989898",
  landline: "0120 4543956",
  mapLink: "https://maps.google.com/?q=Lemon+Tree+Premier+Bangalore",
  checkIn: "Jan 18, 11:30 am",
  checkOut: "Jan 19, 12:00 pm",
  services: [
    { label: "Airport Pickup", value: "Yes" },
    { label: "Tea / Coffee", value: "Yes" },
    { label: "Laundry", value: "1 set of 5 pc/day" },
    { label: "Meal", value: "Breakfast" },
  ],
};

export const dummyRes = [
  {
    id: "682420ded228936ba936e644",
    dep: "DEL",
    arr: "SIN",
    fltdate: "2025-05-10T00:00:00Z",
    fltNbr: "1013",
    picApprovalStatus: 10,
    lspApprovalStatus: 10,
    isLSPApprovalRequired: true,
    isPICApprovalRequired: true,
    approvalStatus: "Pending",
    allowRemoval: true,
  },
  {
    id: "68243958386741e1fe8da806",
    dep: "DEL",
    arr: "SIN",
    fltdate: "2025-05-10T00:00:00Z",
    fltNbr: "1013",
    picApprovalStatus: 10,
    lspApprovalStatus: 10,
    isLSPApprovalRequired: true,
    isPICApprovalRequired: true,
    approvalStatus: "Pending",
    allowRemoval: true,
  },
];

export const initialRequestData: RequestItem[] = [
  {
    id: "68134eb7b97d22e57d15db69",
    dep: "DEL",
    arr: "ATQ",
    fltDate: "2025-04-17T00:00:00Z",
    fltNbr: "2045",
    picApprovalStatus: 1,
    lspApprovalStatus: 0,
    isLSPApprovalRequired: false,
    isPICApprovalRequired: true,
    approvalStatus: "Approved",
    allowRemoval: true,
  },
];

// export const dummyToken =
//   "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyIsImtpZCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyJ9.eyJhdWQiOiJhcGk6Ly82NzNhMjhhYi0wZGEzLTRlOWYtOGJlMi0wZDdkZDM4Zjg3ODkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83M2YyZTcxNC1hMzJlLTQ2OTctOTQ0OS1kZmZlMWRmOGE1ZDUvIiwiaWF0IjoxNzE5NTQ5NjgwLCJuYmYiOjE3MTk1NDk2ODAsImV4cCI6MTcxOTU1NDQ2NSwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhYQUFBQW9yVCt1enV0Y255MVJRS2RvRE55d0hZRVBSSkZINU5zQS9RK1pEM2ppN2gvajFRUHBPRTI4LzNBRWZnTU1XWkw3YWpMZG9MYk9LWGtMQ3JYbjRYSWhFZDJScE9STFRmdElwMkdmdzJKbEtzPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwaWQiOiI2NzNhMjhhYi0wZGEzLTRlOWYtOGJlMi0wZDdkZDM4Zjg3ODkiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6Ik1vZGgiLCJnaXZlbl9uYW1lIjoiS3JhdGlrIiwiaXBhZGRyIjoiMTE1LjExNC4xMi4yMzQiLCJuYW1lIjoiS3JhdGlrIE1vZGggKERpZ2l0YWwsSVNDKShYLVN0YXR1c05lbykiLCJvaWQiOiI4NmJhZGQ3ZC04MDRiLTQzYmEtYjQxMS1kNGUxYWI1MGRlMzMiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMjc4MzExNDkyMi0yODE3MDAxMTczLTMzMzk1ODgyNDYtMjMxOTY3IiwicmgiOiIwLkFWTUFGT2Z5Y3k2amwwYVVTZF8tSGZpbDFhc29PbWVqRFo5T2ktSU5mZE9QaDRuRkFJOC4iLCJzY3AiOiJCQS1BcHAiLCJzdWIiOiJrOXJBTllmMXRzVlZ0c29qTjFLM3ZHcjVRY0JCT28zTHQ0TkF4Wi1Hd00wIiwidGlkIjoiNzNmMmU3MTQtYTMyZS00Njk3LTk0NDktZGZmZTFkZjhhNWQ1IiwidW5pcXVlX25hbWUiOiJLcmF0aWsueC5Nb2RoQEdvSW5kaWdvLmluIiwidXBuIjoiS3JhdGlrLnguTW9kaEBHb0luZGlnby5pbiIsInV0aSI6Im5XbDViOTNsOVVtekhVdkxZanVVQUEiLCJ2ZXIiOiIxLjAifQ.KApBleOGF0PBoE2CMyE5ydh31ff450aQtPIIESG0TjK7RC3xhQxC5-zKYJ-M5AUhl4ueyoiD0LM7o7E44SGqVjN_-KZ8QXXzBGyJjrsLc3grRXHPh8PYJtlR-PJvl0KyjPoTLvK5vEPkKTvsCjBe3024y5TOQTHadaL6WZspNYu9ZNtB9Nd5SKxLftofrTkZgEk9QJpdPJiUvSyNOB1IS7ywMrm9tAPosT0rAi-JbBM_8uR3yW7u-WQI7pFIvsVcM5xyJATC3OIIDclG7r_odlr3NZxS_iz_nvCfenZJMTlQXMiGlOVstTOJ22cNTvzTYJZH13Y-SrHxu5dkgdwQmQ";

export const dummyToken = "YXgLD8NGqanCon8hA7d4wChwwT5jLlMSNnMOU1f260F";

export const folders = [
  { id: 1, title: "ACM" },
  { id: 2, title: "Logistics" },
  { id: 3, title: "Documents" },
  { id: 4, title: "Links Library" },
  { id: 5, title: "Sector Pay" },
  { id: 6, title: "Allowance" },
  { id: 7, title: "Logistics" },
  { id: 8, title: "CPFO" },
  { id: 9, title: "Videos" },
  { id: 10, title: "PMLS" },
  { id: 11, title: "LPA" },
  { id: 12, title: "Letters" },
  { id: 13, title: "BluePoints" },
  { id: 14, title: "Open Flight" },
  { id: 15, title: "Bidding" },
  { id: 16, title: "Trip Trade" },
  { id: 17, title: "Catering" },
  { id: 18, title: "AEP" },
  { id: 19, title: "Uniform" },
];

export const triggerRosterCodes = ["SCK", "EML"];

export const rosterCodeResponse = {
  isSuccess: true,
  message: "Data Found",
  data: {
    myRoster: ["FLT", "SCK"],
    leadershipPilots: [
      {
        iga: "IGA001",
        email: "pilot1@example.com",
        name: "Captain John Doe",
      },
      {
        iga: "IGA002",
        email: "pilot2@example.com",
        name: "Captain Jane Smith",
      },
      {
        iga: "IGA003",
        email: "pilot3@example.com",
        name: "Captain Mike Brown",
      },
    ],
  },
  statusCode: 200,
  isData: true,
};

export const manageRequestDummyData = [
  {
    id: "6836a038d553b491a9db8fbe",
    dep: "DEL",
    arr: "IDR",
    fltDate: "2025-05-28T00:00:00Z",
    fltNbr: "314",
    ldcpApprovalStatus: 10,
    isLDCPApprovalRequired: false,
    approvalStatus: 0,
    allowRemoval: false,
    ldcpiga: 0,
    ldcpUpdatedOn: null,
    isPICApprovalRequired: true,
    picIGA: 41685,
    picApprovalStatus: 10,
    picUpdatedOn: null,
    picComments: "",
    ldcpComments: null,
    requesterIGA: 24264,
    requesterName: "Shashni, Tashi Angmo",
    travelReason: "Reason",
    requesterRosterCode: ["OFG ", "SBY ", "ASBI"],
  },
  {
    id: "6836a038d113b491a9db8fbe",
    dep: "DEL",
    arr: "BOM",
    fltDate: "2025-05-28T00:00:00Z",
    fltNbr: "254",
    ldcpApprovalStatus: 10,
    isLDCPApprovalRequired: false,
    approvalStatus: 0,
    allowRemoval: false,
    ldcpiga: 0,
    ldcpUpdatedOn: null,
    isPICApprovalRequired: true,
    picIGA: 41685,
    picApprovalStatus: 10,
    picUpdatedOn: null,
    picComments: "",
    ldcpComments: null,
    requesterIGA: 24264,
    requesterName: "Shashni, Tashi Angmo",
    travelReason: "Reason",
    requesterRosterCode: ["OFG ", "SBY ", "ASBI"],
  },
  {
    id: "6836a038d553b231a9db8fbe",
    dep: "DEL",
    arr: "BOM",
    fltDate: "2025-05-28T00:00:00Z",
    fltNbr: "102",
    ldcpApprovalStatus: 10,
    isLDCPApprovalRequired: false,
    approvalStatus: 0,
    allowRemoval: false,
    ldcpiga: 0,
    ldcpUpdatedOn: null,
    isPICApprovalRequired: true,
    picIGA: 41685,
    picApprovalStatus: 10,
    picUpdatedOn: null,
    picComments: "",
    ldcpComments: null,
    requesterIGA: 24264,
    requesterName: "Shashni, Tashi Angmo",
    travelReason: "Reason",
    requesterRosterCode: ["OFG ", "SBY ", "ASBI"],
  },
  {
    id: "6896a038d113b491a9db8fbe",
    dep: "DEL",
    arr: "MAA",
    fltDate: "2025-05-28T00:00:00Z",
    fltNbr: "254",
    ldcpApprovalStatus: 10,
    isLDCPApprovalRequired: false,
    approvalStatus: 0,
    allowRemoval: false,
    ldcpiga: 0,
    ldcpUpdatedOn: null,
    isPICApprovalRequired: true,
    picIGA: 41685,
    picApprovalStatus: 10,
    picUpdatedOn: null,
    picComments: "",
    ldcpComments: null,
    requesterIGA: 24264,
    requesterName: "Shashni, Tashi Angmo",
    travelReason: "Reason",
    requesterRosterCode: ["OFG ", "SBY ", "ASBI"],
  },
  {
    id: "6836a038d5511b231a9db8fbe",
    dep: "DEL",
    arr: "AGR",
    fltDate: "2025-05-28T00:00:00Z",
    fltNbr: "102",
    ldcpApprovalStatus: 10,
    isLDCPApprovalRequired: false,
    approvalStatus: 0,
    allowRemoval: false,
    ldcpiga: 0,
    ldcpUpdatedOn: null,
    isPICApprovalRequired: true,
    picIGA: 41685,
    picApprovalStatus: 10,
    picUpdatedOn: null,
    picComments: "",
    ldcpComments: null,
    requesterIGA: 24264,
    requesterName: "Shashni, Tashi Angmo",
    travelReason: "Reason",
    requesterRosterCode: ["OFG ", "SBY ", "ASBI"],
  },
];

export const crewDummyApiData = {
  success: true,
  message: "",
  data: [
    {
      crews: [
        {
          iga: 20585,
          name: "Bhat, Shradha Pandurang",
          email: "SHRADHA.BHAT@GOINDIGO.IN",
          phoneNumber: "9664389355",
          category: "LD",
          dutyType: "FLT",
          isACM: "YES",
          isPIC: false,
          boardingType: "Local Boarding",
          transitFlightNumber: "",
          baStatus: "Incompleted",
          baCheckInTime: "",
        },
        {
          iga: 35287,
          name: "KUMAR, TINAMUNI K",
          email: "Tinamuni.Kumar@goindigo.in",
          phoneNumber: "9004853446",
          category: "FO",
          dutyType: "FLT",
          isACM: "NO",
          isPIC: false,
          boardingType: "Transit: 12312312",
          transitFlightNumber: "",
          baStatus: "Completed",
          baCheckInTime: "23:59",
        },
        {
          iga: 46099,
          name: "BHERULAL, PUNAMIYA ROHIT",
          email: "Rohit.Punamiya@goindigo.in",
          phoneNumber: "9967037775",
          category: "CP",
          dutyType: "FLT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
        {
          iga: 48371,
          name: "Pandey, Kritika",
          email: "Kritika.Pandey2@GOINDIGO.IN",
          phoneNumber: "7905026873",
          category: "LD",
          dutyType: "DHT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
        {
          iga: 63597,
          name: "Kumawat, Rashmi Gopal",
          email: "Rashmi.Kumawat@GOINDIGO.in",
          phoneNumber: "8459292871",
          category: "CA",
          dutyType: "FLT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
        {
          iga: 63693,
          name: "Rawat, Khushi",
          email: "Khushi.Rawat@GOINDIGO.in",
          phoneNumber: "7042817822",
          category: "CA",
          dutyType: "DHT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
        {
          iga: 66398,
          name: "K Kudalkar ,Sahana",
          email: "Sahana.Kudalkar@GOINDIGO.in",
          phoneNumber: "8951577382",
          category: "CA",
          dutyType: "FLT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
        {
          iga: 70568,
          name: "Priyanka, Lalwani",
          email: "Priyanka.Lalwani@GOINDIGO.in",
          phoneNumber: "9068702806",
          category: "CA",
          dutyType: "DHT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
        {
          iga: 76038,
          name: "Sah, Sukriti",
          email: "Sukriti.Sah@GOINDIGO.IN",
          phoneNumber: "8433093457",
          category: "CA",
          dutyType: "DHT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
        {
          iga: 76089,
          name: "Newar, Christina",
          email: "Christina.Newar@GOINDIGO.IN",
          phoneNumber: "9101323169",
          category: "CA",
          dutyType: "FLT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
        {
          iga: 89041,
          name: "Tomar Vaishali",
          email: "VAISHALI.TOMAR@GOINDIGO.IN",
          phoneNumber: "7840026144",
          category: "CA",
          dutyType: "DHT",
          isACM: "NO",
          isPIC: false,
          boardingType: "",
          transitFlightNumber: "",
          baStatus: "",
          baCheckInTime: "",
        },
      ],
    },
  ],
  error: [],
};

export const mainScreenRoster = {
  success: true,
  message: "",
  data: [
    {
      rosters: {
        "2025-08-04T00:00:00": [
          {
            day: "2025-08-04T00:00:00",
            dutyType: "FLT",
            dutyTypeName: "Flight",
            startDateTime: "2025-08-04T03:00:00",
            endDatetime: "2025-08-04T04:55:00",
            dutyDetails: {
              arr: "PAT",
              dep: "HYD",
              arrTerminal: "",
              depTerminal: "",
              startTimeUTC: "2025-08-04T03:00:00",
              endTimeUTC: "2025-08-04T04:55:00",
              startTimeLocal: "2025-08-04T08:30:00",
              endTimeLocal: "2025-08-04T10:25:00",
              arrTimeDiff: "330",
              depTimeDiff: "330",
              carrier: "6E",
              flightNumber: "6719",
              bayNo: null,
              acType: "320",
              reqNo: "VTITN",
              tsStatus: null,
              gateNo: null,
              config: "Y186VV10",
              type: "LHS",
              code: "J",
              status: "",
              baStatus: null,
              passengerLoad: "0",
              trainingName: null,
              instructor: "GAGANDEEP  JUNEJA",
              trainee: "PARTH  SETHI",
            },
          },
          // {
          //   day: "2025-08-04T00:00:00",
          //   dutyType: "OFM",
          //   dutyTypeName: "Leave",
          //   startDateTime: "2025-08-04T08:30:00",
          //   endDatetime: "2025-08-04T11:30:00",
          //   dutyDetails: null,
          // },
          // {
          //   day: "2025-08-04T00:00:00",
          //   dutyType: "FLT",
          //   dutyTypeName: "Flight",
          //   startDateTime: "2025-08-04T05:30:00",
          //   endDatetime: "2025-08-04T07:40:00",
          //   dutyDetails: {
          //     arr: "HYD",
          //     dep: "PAT",
          //     arrTerminal: "",
          //     depTerminal: "",
          //     startTimeUTC: "2025-08-04T05:30:00",
          //     endTimeUTC: "2025-08-04T07:40:00",
          //     startTimeLocal: "2025-08-04T11:00:00",
          //     endTimeLocal: "2025-08-04T13:10:00",
          //     arrTimeDiff: "330",
          //     depTimeDiff: "330",
          //     carrier: "6E",
          //     flightNumber: "432",
          //     bayNo: null,
          //     acType: "320",
          //     reqNo: "VTITN",
          //     tsStatus: null,
          //     gateNo: null,
          //     config: "Y186VV10",
          //     type: "LHS",
          //     code: "J",
          //     status: "In-Flight",
          //     baStatus: null,
          //     passengerLoad: "0",
          //     trainingName: null,
          //     instructor: "GAGANDEEP  JUNEJA",
          //     trainee: "PARTH  SETHI",
          //   },
          // },
        ],
      },
    },
  ],
  error: [],
};

export const realData = {
  hotels: [
    {
      hotelName: "Sunrise Inn",
      address: "123 Ocean Drive, Beach City",
      contactNumber: "+1-234-567-8901",
      emailList: [
        { email: "contact@sunriseinn.com" },
        { email: "support@sunriseinn.com" },
      ],
      phoneList: [
        { phoneNumber: "+1-234-567-8901" },
        { phoneNumber: "+1-234-567-8902" },
      ],
      checkInTime: "2025-08-05T14:00:00",
      checkInTimeLocal: "2025-08-05T14:00:00",
      checkOutTime: "2025-08-07T11:00:00",
      checkOutTimeLocal: "2025-08-07T11:00:00",
    },
  ],
  transportBeforeFlight: [
    {
      transportStatus: "Pending !",
      vehicleNumber: "BUS-101",
      transporterName: "CityLine Travels",
      vehicleType: "Mini Bus",
      pickupAddress:
        "Indigo Office Emmar Capital Tower 2, Sector 26, Gurugram, HR. 122002",
      dropAddress:
        "Indira Gandhi International Airport, New Delhi, Delhi 110037 Terminal -3",
      pickDateTime: "2025-08-07T17:00:00",
      pickDateTimeLocal: "2025-08-07T18:00:00",
      dropDatetime: "2025-08-07T18:00:00",
      dropDatetimeLocal: "2025-08-07T18:00:00",
      drivers: [
        {
          driverName: "John Smith",
          driverContactNumber: "+1-222-333-4444",
        },
      ],
    },
  ],
  transportAfterFlight: [
    {
      transportStatus: "Confirmed !",
      vehicleNumber: "CAR-202",
      transporterName: "SpeedRide",
      vehicleType: "Sedan",
      pickupAddress: "Airport Terminal 2",
      dropAddress: "Downtown Hotel",
      pickDateTime: "2025-08-07T17:00:00",
      pickDateTimeLocal: "2025-08-07T18:00:00",
      dropDatetime: "2025-08-07T18:00:00",
      dropDatetimeLocal: "2025-08-07T18:00:00",
      drivers: [
        {
          driverName: "Emily Davis",
          driverContactNumber: "+1-555-666-7777",
        },
      ],
    },
  ],
};
