export const Strings = {
  utc: "utc",
  UTC: "UTC",
  localTime: "Local Time",
  local: "local",
  checkIn: "Check In",
  checkOut: "Check Out",
  status: "Status",
  pickUp: "Pick up",
  dropOff: "Drop off",
  driverName: "Driver Name",
  contactNumber: "Contact Number",
  company: "Company",
  vehicleType: "Vehicle Type",
  hotelDetails: "Hotel Details",
  vehicleNumber: "Vehicle Number",
  transportDetails: "Transport Details",
  metar: "Metar",
  services: "Services",
  taf: "TAF",
  rejectedStatus: 30,
  appName: "6E Aviate",
  Hello: "Hello",
  additionalCrewMember: "Additional Crew Member",
  searchFlight: "Search Flight",
  recentSearch: "Recent Search",
  myRequest: "My Request",
  picApproval: "PIC Approval",
  weFound: "We found # flight for",
  apply: "Apply",
  rosterCode: "Roster Code",
  leaderShipPilotApproval: "Leadership Pilot Approval",
  pleaseCheckSourceDestination: "Please check the source and destination",
  from: "From",
  source: "Source",
  to: "To",
  dep: "Dep",
  noDataFound: "No Data Found",
  roasterCode: "Roster Code",
  destination: "Destination",
  travelDate: "Travel Date",
  flightNumber: "Flight Number",
  flightType: "Flight Type",
  flightStatus: "Flight Status",
  flightTime: "Flight Time",
  flightDuration: "Flight Duration",
  totalRequest: "Total Request",
  accepted: "Accepted",
  departure: "Departure",
  arrival: "Arrival",
  travelReason: "Travel Reason",
  pleaseProvideReason: "Please provide a reason for your travel",
  selectLeadershipPilot: "Select Leadership Pilot",
  termsCond: "Terms and Conditions",
  pleaseAgreeToTerms: "Please agree to the terms.",
  MyRequestsStringsHeading: "My Request",
  deleteRequestTitle: "Delete Request",
  deleteRequestMessage: "Are you sure you want to delete this request?",
  deleteCancel: "Cancel",
  deleteDelete: "Delete",
  flight: "Flight",
  rejected: "Rejected",
  pending: "Pending",
  approved: "Approved",
  cancelled: "Cancelled",
  emergency: "A medical emergency",
  pilotComment: "Approved",
  picComment: "PIC Comments",
  picCommentForReject: "PIC Comment",
  roasterCodeForManageRequest: "Roster Code",
  leadershipComment: "Leadership Pilot Comment",
  approve: "Approve",
  reject: "Reject",
  string: "string",
  headerTitle: "Additional Crew Member",
  flightDetails: "Flight Details",
  sourceAndDestinationSame: "Source and destination cannot be the same",
  ok: "Ok",
  internalServer: "Internal Server Error",
  somethingPleaseTryAgain: "Some error occurred please try again",
  pleaseTryAgain: "Please try again after some time.",
  noFlightFound: "No flight found",
  invalidSourceOrDestination: "Invalid source or destination",
  origin: "Origin",
  pleaseEnterIga: "Please enter IGA",
  inappropriateWords: "Please keep appropriate words for your reason",
  all: "all",
  commentBeforeRejecting:
    "Please provide a comment before rejecting the request",
  commentBeforeApproving:
    "Please provide a comment before approving the request",
  dutyDetails: "Duty Details",
  dutyTimeStatistics: "Duty Time Statistics",
  cockpitCrew: "Cockpit Crew",
  cabinCrew: "Cabin Crew",
  SCK: "SCK",
  VAC: "VAC",
  OFG: "OFG",
  SMT: "SMT",
  fullDay: "Full Day",
  requested: "Requested",
  specialActivity: "Special Activity",
  location: "Location",
  dutyDetailsScreen: "DutyDetailsScreen",
  seeAllRevisions: "See all Revisions",
  sby: "SBY", // Standby
  FLT: "FLT", // flight
  favourites: "Favourites",
  leave: "Leave",
  training: "Training",
  officeDuty: "Office Duty",
  standby: "Standby",
  flightDuty: "flightDuty",
  memoDetails: "Memo Details",
  debriefing: "Debriefing",
  blankDay: "Blank Day",
  noDataAvailable:"No Data Available"
};

export const dateFormat = {
  fullDate: "YYYY-MM-DD",
  day: "ddd",
  date: "DD",
  month: "MMM",
  time: "HH:mm",
  time12Hour: "hh:mm A",
  dateTime: "YYYY-MM-DD HH:mm",
  dateTime12Hour: "YYYY-MM-DD hh:mm A",
  monthYear: "MMM YYYY",
  monthYearShort: "MMM YY",
  year: "YYYY",
  timeWithSeconds: "HH:mm:ss",
  timeWithSeconds12Hour: "hh:mm:ss A",
  dateWithTime: "YYYY-MM-DD HH:mm:ss",
  dateWithTime12Hour: "YYYY-MM-DD hh:mm:ss A",
};
